#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source /opt/resource/common.sh

# Read inputs
source=$1
payload=$(mktemp $TMPDIR/helm-resource-request.XXXXXX)
cat > $payload <&0

# Prepare
setup_resource $payload $source
echo "Resource setup successful."

# Parse parameters
namespace=$(jq -r '.source.namespace // "default"' < $payload)
chart=$(jq -r '.params.chart // ""' < $payload)
version=$(jq -r '.params.version // ""' < $payload)
release_file=$(jq -r '.params.release // ""' < $payload)
values=$(jq -r '.params.values // ""' < $payload)
wait_until_ready=$(jq -r '.params.wait_until_ready // 0' < $payload)
debug=$(jq -r '.params.debug // "false"' < $payload)
replace=$(jq -r '.params.replace // "false"' < $payload)
delete=$(jq -r '.params.delete // "false"' < $payload)
if [ -z "$chart" ]; then
  echo "invalid payload (missing chart)"
  exit 1
fi
if [ -n "$release_file" ]; then
  release=`cat $source/$release_file`
else
  release=$(jq -r '.source.release // ""' < $payload)
fi

if [[ "$chart" == *.tgz ]]; then
  # it's a file
  chart_full="$source/$chart"
  version=""
else
  # get from a repo
  chart_full="$chart"
fi

is_deployed() {
  if [ -n "$1" ]; then
    set +e
    helm status $1 | grep "STATUS: DEPLOYED" > /dev/null
    if [ $? = 0 ]; then
      # exists and is deployed
      echo true
    else
      # not deployed at the moment
      echo false
    fi
    set -e
  else
    echo false
  fi
}

helm_install() {
  helm_cmd="helm install"
  helm_cmd="$helm_cmd --namespace $namespace"
  if [ -n "$release" ]; then
    helm_cmd="$helm_cmd -n $release"
  fi
  if [ -n "$values" ]; then
    helm_cmd="$helm_cmd -f $source/$values"
  fi
  if [ "$replace" = true ]; then
    helm_cmd="$helm_cmd --replace"
  fi
  if [ "$debug" = true ]; then
    helm_cmd="$helm_cmd --dry-run --debug"
  fi
  if [ -n "$version" ]; then
    helm_cmd="$helm_cmd --version $version"
  fi
  logfile="/tmp/log"
  mkdir -p /tmp
  $helm_cmd $chart_full | tee $logfile

  # Find the name of the release
  release=`cat $logfile | grep "NAME:" | awk '{print $2}'`
}

# Find the current revision of a helm release
current_revision() {
  revision=`helm history $release | grep "DEPLOYED" | awk '{print $1}'`
  echo $revision
}

helm_upgrade() {
  helm_cmd="helm upgrade $release"
  if [ -n "$values" ]; then
    helm_cmd="$helm_cmd -f $source/$values"
  fi
  if [ "$debug" = true ]; then
    helm_cmd="$helm_cmd --dry-run --debug"
  fi
  if [ -n "$version" ]; then
    helm_cmd="$helm_cmd --version $version"
  fi
  logfile="/tmp/log"
  mkdir -p /tmp
  set -x
  $helm_cmd $chart_full | tee $logfile
  set +x
}

helm_delete() {
  if [ -z "$release" ]; then
    echo "invalid payload (missing release if delete=true)"
    exit 1
  fi
  echo "Deleting the release $release..."
  helm_cmd="helm delete"
  if [ "$debug" = true ]; then
    helm_cmd="$helm_cmd --dry-run --debug"
  fi
  logfile="/tmp/log"
  mkdir -p /tmp
  $helm_cmd $release| tee $logfile
}

wait_ready() {
  if [ -n "$wait_until_ready" ] && [ "$wait_until_ready" -gt "0" ]; then
    echo "Waiting until deployment of $release is ready..."
    node /opt/wait-for-helm-deployment/src/index.js $release $wait_until_ready
  fi
}


if [ "$delete" = true ]; then
  helm_delete
  result="$(jq -n "{version:{release:\"$release\", deleted: \"true\"}, metadata: [{name: \"release\", value: \"$release\"}]}")"
  echo "$result" | jq -s add  >&3
else
  if [ "$(is_deployed $release)" = true ]; then
    echo "Upgrading $release"
    helm_upgrade
  else
    echo "Installing $release"
    helm_install
  fi

  revision=$(current_revision)
  echo "Deployed revision $revision of $release"
  wait_ready
  result="$(jq -n "{version:{release:\"$release\", revision:\"$revision\"}, metadata: [{name: \"release\", value: \"$release\"},{name: \"revision\", value: \"$revision\"}]}")"
  echo "$result" | jq -s add  >&3
fi
